// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: billing_service.proto
// Protobuf Java Version: 4.29.1

package billing;

public interface BillingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BillingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * so this 1 or any number is helping protocol puffer to identify the field and its type when it serialize and deserialize the data
   * </pre>
   *
   * <code>string patientId = 1;</code>
   * @return The patientId.
   */
  java.lang.String getPatientId();
  /**
   * <pre>
   * so this 1 or any number is helping protocol puffer to identify the field and its type when it serialize and deserialize the data
   * </pre>
   *
   * <code>string patientId = 1;</code>
   * @return The bytes for patientId.
   */
  com.google.protobuf.ByteString
      getPatientIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string email = 3;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 3;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();
}
